# Generated by Django 5.1.2 on 2026-03-26 09:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_club'),
    ]

    operations = [
        migrations.AlterField(
            model_name='club',
            name='content',
            field=models.TextField(blank=True, verbose_name='Мазмұны'),
        ),
        migrations.CreateModel(
            name='ClubMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=255, verbose_name='Аты-жөні')),
                ('info', models.CharField(blank=True, max_length=200, verbose_name='Қосымша ақпарат (сыныбы т.б.)')),
                ('club', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='members', to='app.club', verbose_name='Үйірме')),
            ],
            options={
                'verbose_name': 'Қатысушы',
                'verbose_name_plural': 'Қатысушылар',
            },
        ),
        migrations.CreateModel(
            name='ClubSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.CharField(max_length=50, verbose_name='Күн')),
                ('time', models.CharField(max_length=100, verbose_name='Уақыт')),
                ('club', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='schedules', to='app.club', verbose_name='Үйірме')),
            ],
            options={
                'verbose_name': 'Кесте',
                'verbose_name_plural': 'Кестелер',
            },
        ),
    ]
