# Generated by Django 5.1.2 on 2026-03-26 09:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_alter_club_content_clubmember_clubschedule'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClubImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='clubs/gallery/', verbose_name='Сурет')),
                ('caption', models.CharField(blank=True, max_length=200, verbose_name='Сипаттама')),
                ('club', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='app.club', verbose_name='Үйірме')),
            ],
            options={
                'verbose_name': 'Үйірме суреті',
                'verbose_name_plural': 'Үйірме галереясы',
            },
        ),
    ]
